export const fakeAds = [
    {
        id: 1,
        imageUrl: "https://via.placeholder.com/150",
        address: "כיכר דיזינגוף 7",
        city: "תל אביב יפו",
        rooms: 1,
        floor: 2,
        price: "₪4,500",
        Square_meter: 45,
        description: 'יחידת דיור שני חדרים , עליונה בוילה , כניסה נפרדת, נמצא באיזור וילות , ליד : המכללה למנהל קניון הזהב, סינמה סיטי , 10דקות מהים, בקרבת מקום כבישים 4 , 20 , 431',
        entryDate: "2023-01-01",
        features: {
            elevator: "yes",
            blending: "no",
            renovated: "yes",
            disabledAccess: "no",
            bars: "yes",
            MMD: "no",
            airConditioner: "yes",
            warehouse: "no",
            solarHeater: "yes",
            furnished: "no",
            parking: "yes"
        },
        leaseContract: "path/to/leaseContract.pdf"
    },
    {
        id: 2,
        imageUrl: "https://via.placeholder.com/150",
        address: "טשרניחובסקי 3",
        city: "באר שבע",
        rooms: 5,
        floor: 8,
        price: "₪10,500",
        Square_meter: 100,
        description: 'יחידת דיור שני חדרים , עליונה בוילה , כניסה נפרדת, נמצא באיזור וילות , ליד : המכללה למנהל קניון הזהב, סינמה סיטי , 10דקות מהים, בקרבת מקום כבישים 4 , 20 , 431',
        entryDate: "2023-01-01",
        features: {
            elevator: "yes",
            blending: "no",
            renovated: "yes",
            disabledAccess: "no",
            bars: "yes",
            MMD: "no",
            airConditioner: "yes",
            warehouse: "no",
            solarHeater: "yes",
            furnished: "no",
            parking: "yes"
        },
        leaseContract: "path/to/leaseContract.pdf"
    },
    {
        id: 3,
        imageUrl: "https://via.placeholder.com/150",
        address: "כיכר דיזינגוף 6",
        city: "תל אביב יפו",
        rooms: 1,
        floor: 2,
        price: "₪4,500",
        Square_meter: 45,
        description: 'יחידת דיור שני חדרים , עליונה בוילה , כניסה נפרדת, נמצא באיזור וילות , ליד : המכללה למנהל קניון הזהב, סינמה סיטי , 10דקות מהים, בקרבת מקום כבישים 4 , 20 , 431',
        entryDate: "2023-01-01",
        features: {
            elevator: "yes",
            blending: "no",
            renovated: "yes",
            disabledAccess: "no",
            bars: "yes",
            MMD: "no",
            airConditioner: "yes",
            warehouse: "no",
            solarHeater: "yes",
            furnished: "no",
            parking: "yes"
        },
        leaseContract: "path/to/leaseContract.pdf"
    },
    {
        id: 4,
        imageUrl: "https://via.placeholder.com/150",
        address: "טשרניחובסקי 3",
        city: "באר שבע",
        rooms: 5,
        floor: 8,
        price: "₪10,500",
        Square_meter: 100,
        description: 'יחידת דיור שני חדרים , עליונה בוילה , כניסה נפרדת, נמצא באיזור וילות , ליד : המכללה למנהל קניון הזהב, סינמה סיטי , 10דקות מהים, בקרבת מקום כבישים 4 , 20 , 431',
        entryDate: "2023-01-01",
        features: {
            elevator: "yes",
            blending: "no",
            renovated: "yes",
            disabledAccess: "no",
            bars: "yes",
            MMD: "no",
            airConditioner: "yes",
            warehouse: "no",
            solarHeater: "yes",
            furnished: "no",
            parking: "yes"
        },
        leaseContract: "path/to/leaseContract.pdf"
    },
];